# Site settings
title: Hitting the Refresh Button
header-img: img/home-bg.png
email: klpapke215@gmail.com
copyright_name: klpapke215
description: > # this means to ignore newlines until "baseurl:"
  My quest to expand my career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  klpapke215
learn_profile: klpapke215
email_username: klpapke215@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
